<h2>This is the Student Page</h2>


<div id="welcome">
Welcome, <strong><?= $this->userInfo['first_name'] ?> <?= $this->userInfo['last_name']; ?></strong>
<p>Yourd current program is <strong><?= $this->roledesc->description; ?></strong></p>

</div>

<hr>
<button type="button" onClick="parent.location='studentartifact'">Upload Artifacts</button>   <button type="button" onClick="parent.location='standards'">Manage Portfolio</button>

<br><br>

<hr>
<br>

<div id="uploads">
	<strong>Recent Uploads</strong>
	<br>
	<?php echo "<table id=\"uploaded_artifacts_table\">";?>
	<?php echo "<tr>";
	  echo "<th>Artifact Title</th>";
	  echo "</tr>";
	?>
	<?= $this->partialLoop('partials/uploadRow.phtml', $this->uploads) ?>
	<?php echo "</table>" ?>
	<br>
</div>

<div id="linked">
	<strong>Recent Linked Artifacts</strong>
	<?php echo "<table id=\"linked_table\">";?>
	<?php echo "<tr>";
	  echo "<th>Artifact Title</th>";
	  echo "<th>Course</th>";
	  echo "<th>Standard</th>";
	  echo "<th>Indicator</th>";
	  echo "</tr>";
	?>
	<?= $this->partialLoop('partials/linkedArtifactRow.phtml', $this->links) ?>
	<?php echo "</table>" ?>
	<br>
</div>


<div id="submissions">
	<strong>Recent Submissions</strong>
	<br>
	<?php echo "<table id=\"submitted_table\">";?>
	<?php echo "<tr>";
	  echo "<th>Artifact Title</th>";
	  echo "<th>Course</th>";
	  echo "<th>Standard</th>";
	  echo "<th>Indicator</th>";
	  echo "<th>Professor</th>";
	  echo "</tr>";
	?>
	<?= $this->partialLoop('partials/submissionRow.phtml', $this->submit) ?>
	<?php echo "</table>" ?>
	<br>
</div>



<div id="feedback">
	<strong>Recent Feedback</strong>
	<br>
	<?php echo "<table id=\"eval_table\">";?>
	<?php echo "<tr>";
		echo "<th>Artifact Title</th>";
	  	echo "<th>Course</th>";
	  	echo "<th>Standard</th>";
	  	echo "<th>Indicator</th>";
	  	echo "<th>Professor</th>";
	  	echo "<th>Rating</th>";
	  	echo "</tr>";
	?>
	<?= $this->partialLoop('partials/evaluatedRow.phtml', $this->evaluated);?>
	<?php echo "</table>" ?>
	<br>
</div>

