<div id="welcome">
<h3>Hello <?= $this->first_name; ?> <?= $this->last_name; ?>,</h3>
<p>Standards for program <strong><?= $this->role->description; ?></strong></p>
</div>

<?php echo "<table id=\"standards_by_program_table\" cellpadding='5'>";?>
<?php echo "<tr>";
	  echo "<th>Number</th>";
	  echo "<th>Description</th>";
	  echo "<th>Details</th>";
	  echo "</tr>";
	?>
<?= $this->partialLoop('partials/standards.phtml', $this->stand);?>
<?php echo "</table>" ?>
