<div id="welcome">
<h3>Hello <?= $this->userInfo['first_name']; ?> <?= $this->userInfo['last_name']; ?></h3>
<p>Standards for program <strong><?= $this->roleInfo['role_description']; ?></strong></p>
</div>

<?php echo "<table id=\"standards_by_program_table\" cellpadding='5'>";?>
<?php echo "<tr>";
	  echo "<th>Number</th>";
	  echo "<th>Description</th>";
	  echo "<th>Details</th>";
	  echo "</tr>";
?>

<?php echo $this->partialLoop('partials/standards.phtml', $this->standardsInfo);?>
<?php echo "</table>" ?>
