<h2>Standard: <?= $this->indRowSet[0]['standard_number'] . 
     " -- " . $this->indRowSet[0]['standard_description']?>
</h2>
<br />
<?php 
function disableButton(){
	return "disabled='disabled'";
}

foreach($this->indRowSet as $indrow):
    echo "<h3>Indicator: " . $indrow['indicator_number'];
    echo " -- " . $indrow['indicator_description'] . "</h3>";
        
    echo "<button type='button' onClick=\"parent.location='artifactlink?standard=";
    echo $this->standard_id;
    echo "&standardnum=";
    echo $this->standard_num;
    echo "&indicator=";
    echo $indrow['indicator_id'];
    echo "&indicatornum=";
    echo $indrow['indicator_number'];
    echo "'\">Link New Artifact</button><br /><br />";
	      
    echo "<table id=\"indicator_artifact_table\">";
    echo "<tr>";
    echo "<th>Artifact Title</th>";
    echo "<th>Course</th>";
    echo "<th>Artifact Rating</th>";
    echo "<th>Cover Sheet</th>";
    echo "<th>Cover Sheet Rating</th>";
    echo "<th>Evaluator</th>";
    echo "</tr>";

    // get all artifacts for this indicator
    $indartArray = array();
    $ctr = 0;
    for ($i=0; $i<sizeof($this->indartRowSet); $i++){
    	if ($this->indartRowSet[$i]['indicator_number'] == $indrow['indicator_number']){
    	   $indartArray[$ctr] = $this->indartRowSet[$i];
	   $standard = array("standard_id" => $this->standard_id);
	   $indartArray[$ctr] = array_merge((array)$indartArray[$ctr], (array)$standard);
    	   $ctr++;
	}
    }
    
    echo $this->partialLoop('partials/indicators.phtml', $indartArray);
    echo "</table><br /><br />";
endforeach;
?>
