
<tr>
	<td><?= $this->artifact_title ?></td> 
	<td><?= $this->course_number ?> </td>
	<td><?= $this->artifact_rating  ?> </td>
	<td><?= $this->cover_title ?> </td>
	<td><?= $this->cover_rating ?> </td>
	<td><?= $this->artifact_evaluator_first . " " . $this->artifact_evaluator_last ?> </td>

	<?php
	   $params1 = 'standard=' . $this->standard_id;
	   $params2 = '&indicator=' . $this->indicator_id .
	         '&artifact=' . $this->artifact_id .
	         '&cover='. $this->cover_id .
		 '&air=' . $this->artifact_indicator_rating_id .
	         '&csr=' . $this->cover_rating_id;
	   echo "<td><button type='button'";
	   
	   // disable link button if there already is a faculty assigned
	   if ($this->artifact_evaluator_first){
		echo disableButton();
	   }
	   
	   echo "name='link1' id='link1' onClick=\"parent.location='submitartifact?";
	   echo $params1;
	   echo $params2;
	   echo "'\">";
	   echo "Submit for Approval</button></td>";
	   
	   
	   echo "<td><button type='button'";
	   
	   // removing action triggers show_confirm function
	   $pathstart = 'javascript:show_confirm(\'indicators/remove?';
	   $path = $pathstart . $params1 . $params2;
	   
	   // disable remove button if there already is a faculty assigned
	   if ($this->artifact_evaluator_first){
		echo disableButton();
	   }
	   echo "onClick=";
	   echo $path;
	   echo "',";
	   echo "'indicators?";
	   echo $params1;
	   echo "','Removing')>Remove Artifact Link</button></td>";
	?>
</tr>

