<tr>
	<td><?= $this->student_last_name ?>, <?= $this->student_first_name ?></td>
	<td><?= $this->standard_number ?> </td>
	<td><?= $this->indicator_number ?> </td>
	<td><a href="landing/openartifact?artifact=<?= $this->artifact_id?>">
		<?= $this->artifact_title?> </a></td>
	<td><a href="landing/openreflective?reflective=<?= $this->reflective_statement_id?>">
		<?= $this->reflective_statement_title?> </a></td>
	<td><?= $this->course_number ?> </td>
	<td><?= $this->submitted_timestamp ?> </td>
	<td><?= $this->artifact_rating . ": " . $this->artifact_comment ?> </td>
        <td><?= $this->reflective_rating . ": " . $this->reflective_comment ?> </td>
</tr>
